import { createAdminClient } from '@/lib/supabase/admin';
import { SubmitButton } from '@/components/SubmitButton';
import { saveCalendarSource,crawlCalendarsNow } from './sourceActions';
const input='rounded border border-slate-400 bg-transparent px-2 py-1 text-sm';
export async function CalendarSources(){
  const admin=createAdminClient();if(!admin)return null;
  const [{data:cities},{data:sources,error},{data:mail}]=await Promise.all([
    admin.from('event_cities').select('id,name').order('name').limit(500),
    admin.from('city_event_sources').select('*').order('enabled',{ascending:false}).order('discovered_at',{ascending:false}).limit(100),
    admin.from('welcome_mail_jobs').select('user_id,status,last_error,sent_at').order('due_at',{ascending:false}).limit(20),
  ]);
  return <section className="mt-8 rounded-xl border p-5"><h2 className="text-xl font-bold">Calendar collection</h2><p className="mt-2 text-sm">Enable a calendar to check it daily or every other day. Supports published ICS feeds and structured Event data on webpages. Robots rules are respected; unsupported sites show an explanation.</p>
    {error?<p className="mt-3">Calendar crawling needs migration 0049.</p>:<><form action={crawlCalendarsNow} className="mt-4"><SubmitButton pendingLabel="Collecting…" className={input}>Collect enabled calendars now</SubmitButton></form>
      <form action={saveCalendarSource} className="mt-4 flex flex-wrap gap-2"><select name="cityId" required aria-label="Calendar city" className={input}>{cities?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="url" name="url" required placeholder="https://… calendar or ICS" aria-label="Calendar URL" className={input}/><input name="title" placeholder="Source name" aria-label="Source name" className={input}/><select name="format" aria-label="Source format" className={input}><option value="jsonld">Webpage (structured events)</option><option value="ics">ICS calendar feed</option></select><select name="hours" aria-label="Collection frequency" className={input}><option value="48">Every other day</option><option value="24">Daily</option></select><label className="text-sm"><input type="checkbox" name="enabled"/> Enable collection</label><SubmitButton pendingLabel="Saving…" className={input}>Add source</SubmitButton></form>
      <details className="mt-4"><summary className="cursor-pointer">Manage sources ({sources?.length??0} shown)</summary><ul className="mt-3 space-y-3">{sources?.map(s=><li key={s.id} className="border-t pt-3"><form action={saveCalendarSource} className="flex flex-wrap gap-2"><input type="hidden" name="cityId" value={s.city_id}/><input type="hidden" name="url" value={s.url}/><input type="hidden" name="title" value={s.title}/><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-sm underline">{s.title}</a><select name="format" aria-label={`Format for ${s.title}`} defaultValue={s.format} className={input}><option value="jsonld">Webpage</option><option value="ics">ICS</option></select><select name="hours" aria-label={`Frequency for ${s.title}`} defaultValue={s.interval_hours} className={input}><option value="24">Daily</option><option value="48">Every other day</option></select><label className="text-sm"><input type="checkbox" name="enabled" defaultChecked={s.enabled}/> Enabled</label><SubmitButton pendingLabel="Saving…" className={input}>Save</SubmitButton></form><p className="mt-1 text-xs">{s.last_count} events · {s.last_crawled_at??'Not collected yet'} · {s.last_error??'No errors'}</p></li>)}</ul></details></>}
    <h3 className="mt-6 font-bold">Recent welcome emails</h3><ul className="mt-2 text-xs">{mail?.map(m=><li key={m.user_id}>{m.status} · {m.sent_at??'Not sent'}{m.last_error?` · ${m.last_error}`:''}</li>)}</ul>
  </section>;
}
