-- Peoplearound — 0074 an event you can put on a poster
--
-- Events live inside projects and are readable only to signed-in neighbors.
-- That is right for the app and useless for the lamppost: the whole point of
-- printing a flyer is that a stranger walking past can read it. So an event
-- can now be given a share code, and `/e/<code>` becomes a page anyone can
-- open — the thing a QR code on paper points at.
--
-- Sharing is off until a steward turns it on, one event at a time. Nothing is
-- published by existing: `share_code` starts null everywhere.
--
-- What a stranger sees is deliberately thin — what, when, where, whose
-- project, and how many are coming. public_event() builds that document and
-- nothing else: no names, no attendee list, no ids to walk back into the app
-- with. It is SECURITY DEFINER only because an unauthenticated visitor cannot
-- read `events` at all, and it takes a code rather than an id, so nobody can
-- enumerate events that were never shared.
--
-- Two columns come along because a flyer needs them: a description (what is
-- actually happening, what to bring) and an end time, so "2–4pm" is sayable
-- and calendars stop guessing two hours.
--
-- Idempotent.

alter table public.events
  add column if not exists description text,
  add column if not exists ends_at timestamptz,
  add column if not exists share_code text;

-- One code, one event. The code is generated by the server action that turns
-- sharing on (crypto-random, 8 characters from an alphabet with no look-alike
-- letters), and this is what makes a collision impossible rather than merely
-- unlikely.
create unique index if not exists events_share_code_key
  on public.events (share_code)
  where share_code is not null;

comment on column public.events.share_code is
  'Null until a steward publishes the event. /e/<code> is then public.';

-- The public face of one shared event. Counts, never names.
create or replace function public.public_event(p_code text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    -- The id is here so that "I'm in" can send someone who signs up straight
    -- to the event inside the app. It unlocks nothing on its own: every page
    -- that takes an event id still requires a session.
    'id', e.id,
    'title', e.title,
    'starts_at', e.starts_at,
    'ends_at', e.ends_at,
    'place', e.place,
    'description', e.description,
    'photo_url', e.photo_url,
    'going', (select count(*) from public.rsvps r where r.event_id = e.id),
    'project', jsonb_build_object('title', p.title, 'category', p.category),
    'community', (
      select jsonb_build_object('name', n.name, 'city', n.city)
        from public.neighborhoods n where n.id = p.neighborhood_id
    )
  )
    from public.events e
    join public.projects p on p.id = e.project_id
   where e.share_code = p_code
     and p.state <> 'archived'::project_state;
$$;

revoke all on function public.public_event(text) from public;
grant execute on function public.public_event(text) to anon, authenticated;
